change-id = 131075

[llvm]
targets = "AArch64;ARM;X86;RISCV"
experimental-targets = ""
clang = true
download-ci-llvm = false
version-suffix = ""
ldflags = "-s"
libzstd = true

[build]
docs = false
submodules = false
extended = true
tools = [
    "cargo",
    "src",
    "clippy",
    "rust-analyzer",
    "rustfmt",
    "rust-analyzer-proc-macro-srv",
]
cargo-native-static = true

[install]
prefix = "../out"
sysconfdir = "etc"

[rust]
channel = "nightly"
lld = true
llvm-tools = true
strip = true
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
llvm-has-rust-patches = false
cc = "clang-18"
cxx = "clang++-18"
linker = "clang-18"

[target.aarch64-apple-darwin]
llvm-has-rust-patches = false

[target.x86_64-apple-darwin]
llvm-has-rust-patches = false

[target.x86_64-pc-windows-gnu]
llvm-has-rust-patches = false
cc = "clang"
cxx = "clang++"
linker = "clang"
