change-id = 116881

[llvm]
thin-lto = true
targets = "AArch64;ARM;X86"
experimental-targets = ""
link-shared = true
clang = true
download-ci-llvm = false

[build]
docs = false
submodules = false
extended = true
tools = ["cargo", "src", "clippy", "rust-analyzer", "rustfmt"]
cargo-native-static = true

[install]
prefix = "../out"
sysconfdir = "etc"

[rust]
channel = "nightly"
lld = true
llvm-tools = true
use-lld = true
lto = "thin"

[target.x86_64-unknown-linux-gnu]
llvm-has-rust-patches = false
cc = "clang-14"
cxx = "clang++-14"
linker = "clang-14"
